[package]
name = "budget-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coloriz = "0.2.0"
console = "0.15.7"
dialoguer = "0.11.0"
tui = "0.19.0"
